name: Pruebame

on:
  push:
    branches:
      - master

jobs:
    test:
      runs-on: windows-2019
      steps:
        - name: PruebaOriginalScore
          run: cd src/test/java/hangman/modelo && make GamesScoreTest;

